baseURL: "https://gis.kosame.net/"
languageCode: "ja-jp"
title: "GIS使い_こさめ"
theme: "hyde"

params:
  description: 位置を持つデータは ひとまず地図にのせてみよっ 

menus:
  main:
    - name: "業務内容"
      url: "/services/"
      weight: 1
    - name: "中の人について"
      url: "/about/"
      weight: 2
    # - name: Github
    #   url: https://github.com/username/
    # - name: LinkedIn
    #   url: https://www.linkedin.com/in/username/
