baseURL: "https://gis.kosame.net/"
languageCode: "ja-jp"
title: "GIS使い_こさめ"
theme: "hyde"

params:
  description: "GIS 使い_こさめ は、GIS に関する業務を請け負う個人事業主です。"

menus:
  main:
    - name: "業務案内"
      url: "/services/"
      weight: 1
    - name: "中の人について"
      url: "/about/"
      weight: 2
